#!/bin/python3
from turtle import *
speed(0)
def squre(length,angle):
  for i in range(4):
    forward(length)
    fillcolor('#0f0')
    forward(-length)
    right(angle)
for i in range(40000):
  squre(100,90)
  right(5)
